### ISSUE TITLE
Duplicated code in CardFacade.js

### ISSUE THREAD

**Issue by pcollpcis** [CyberSource/cybersource-plugins-salesforceb2ccommerce#11]
In https://github.com/CyberSource/cybersource-plugins-salesforceb2ccommerce/blob/release-24.1.0/cartridges/int_cybersource_sfra/cartridge/scripts/facade/CardFacade.js
there is a duplicated code section
![image](https://github.com/CyberSource/cybersource-plugins-salesforceb2ccommerce/assets/48240634/e34aea66-a6fa-4058-9ca3-42561d6a8e4f)

**Comment by cybersource-tpi** [comment]
Fixed in release 24.1.1
