### ISSUE TITLE
Error log WSDL invalid mime namespace

### ISSUE THREAD

**Issue by pcollpcis** [CyberSource/cybersource-plugins-salesforceb2ccommerce#12]
The following error is logged

_ERROR PipelineCallServlet|123992080|Sites-.....-Site|CheckoutServices-PlaceOrder|PipelineCall|Notn-vKh8f system.com.demandware.core.script.internal.webservices.AbstractWebReference Sites-....-Site STOREFRONT Notn-vKh8f YwGD4fbAXmb0g3IK-0-00 8398122756371554304 - WSDL [webreferences2.CyberSourceTransaction] in cartridge [int_cybersource_sfra] has an invalid mime namespace of [http://schemas.xmlsoap.org/wsdl/mime/], which will break. It must be set to [http://schemas.xmlsoap.org/wsdl/mime/2004-08-24.xsd]_

It seems to be present since the version 22.1.0 and this commit 
https://github.com/CyberSource/cybersource-plugins-salesforceb2ccommerce/commit/9736ea9abe8b4d27c5ec52020cf893ae08e1d8d8

![image](https://github.com/CyberSource/cybersource-plugins-salesforceb2ccommerce/assets/48240634/1d40e360-4d09-479e-950d-29fd3374326f)

It doesn't seem to have impact on transactions but it creates unecessary log messages

**Comment by cybersource-tpi** [comment]
Fixed in the latest version, 24.1.1.
