### ISSUE TITLE
The latest release (24.1.0) and 23.1.2 is not merged into master

### ISSUE THREAD

**Issue by drewfranklinsonos** [CyberSource/cybersource-plugins-salesforceb2ccommerce#7]
The latest release doesn't seem to be pulled into the master branch https://github.com/CyberSource/cybersource-plugins-salesforceb2ccommerce/compare/master...release-23.1.2

**Comment by schaefers-mobizcorp** [comment]
The latest release is now 24.1.0 and still not pulled into the master branch

**Comment by drewfranklinsonos** [comment]
Thank you so much to the team for completing this!
