### ISSUE TITLE
The compatibility version of SFRA is wrong in v24.1.0 README file

### ISSUE THREAD

**Issue by apponsforce** [CyberSource/cybersource-plugins-salesforceb2ccommerce#9]
Please confirm that the README actually meant that the v24.1.0 cartridge is _not_ compatible with the v5.3.0 version of SFRA - "Release 6.3.0" has to be corrected to read "Release 5.3.0" - because the commit hash `50ee82f` is actually SFRA version 5.3.0.
Also, please confirm whether this latest version works with the latest version of SFRA which is 7.0.0 ?

**Comment by cybersource-tpi** [comment]
The latest released version, 24.1.1 is compatible with SFRA 7.0.
